version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    networks:
      - app-network
    restart: unless-stopped

  eureka-server:
    container_name: cloud-eureka-discovery-service
    build:
      context: ../cloud-eureka-discovery-service
    ports:
      - "8761:8761"
    networks:
      - app-network

  resource-service:
    container_name: resource-service
    environment:
      - DB_URL_RESOURCE=jdbc:postgresql://postgres:5432/resource_service
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - EUREKA_URL=eureka-server
      - POSTGRES_URL=postgres
      - AWS_ACCESS_KEY=${AWS-ACCESS-KEY}
      - AWS_SECRET_KEY=${AWS-SECRET-KEY}
      - AWS_REGION=us-east-1
    build:
      context: ../resource-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - app-network

  song-service:
    container_name: song-service
    environment:
      - DB_URL_SONG=jdbc:postgresql://postgres:5432/song_service
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - EUREKA_URL=eureka-server
      - POSTGRES_URL=postgres
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin: