server:
  port: 0

spring:
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/song_service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: song-service

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA:localhost}:8761/eureka

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true