spring:
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://postgres:5432/song_service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: song-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true